Best BabySitter/Controllers/ParentController.cs
using Best_BabySitter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Best_BabySitter.Controllers
{
    public class ParentController : Controller
    {
        // GET: Parent

        public ActionResult Index()
        {

            if(Session["parentID"] == null){
                return RedirectToAction("Parent_Login","Home");
            }
            Parent parent = SqlDataAccess.getParentData(int.Parse(Session["parentID"].ToString()));
            Session["parentName"] = parent.f_name.Substring(0,1).ToUpper() + "." + parent.l_name.ToUpper();
            TempData["slots"] = SqlDataAccess.getSlots(int.Parse(Session["parentID"].ToString()));
            TempData["openAdvert"] = SqlDataAccess.getOpenAdverts(int.Parse(Session["parentID"].ToString()));
            TempData["appointment"]= SqlDataAccess.getAppointments(int.Parse(Session["parentID"].ToString()),1);
            return View();
        }
        public ActionResult Advert()
        {
            if (Session["parentID"] == null)
            {
                return RedirectToAction("Parent_Login", "Home");
            }
            else
                return View();
        }
        public ActionResult Create_Advert()
        {
            if(Session["parentID"] == null){
                return RedirectToAction("Parent_Login","Home");
            }else
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create_Advert(Advert advert)
        {
            if (ModelState.IsValid)
            {
                int added = SqlDataAccess.createAdvert(advert, int.Parse( Session["parentID"].ToString()));
                if(added!= -1)
                {
                    TempData["alertMessage"] = "Advert Succefully Created";
                    MailManager.NotifySitters(advert);
                    return RedirectToAction("Index");
                }
      
            }
            TempData["errorMessage"] = "Error occured while creating Advert";
            
            return View();
        }
        
        public ActionResult Manage_Advert()
        {
            if(Session["parentID"] == null){
                return RedirectToAction("Parent_Login","Home");
            }
            List <Advert> openAdverts = SqlDataAccess.getOpenAdverts(int.Parse(Session["parentID"].ToString()));
            ViewData["openAdverts"] = openAdverts;
            ViewData["adResponses"] = new List<Sitter>();
            return View() ;
        }

        [HttpPost]
        public JsonResult AdvertDetail(string id)
        {
            int pos = int.Parse(id);
            Session["curAdvert"] = id;
            List<Advert> list = SqlDataAccess.getOpenAdverts(int.Parse(Session["parentID"].ToString()));
            Advert advert = list[int.Parse(Session["curAdvert"].ToString())];
            return Json(list[pos]);
          
        }

        [HttpPost]
        public JsonResult GetResponses(){
            List<Advert> list = SqlDataAccess.getOpenAdverts(int.Parse(Session["parentID"].ToString()));
            Advert advert = list[int.Parse(Session["curAdvert"].ToString())];
            List<Sitter> sitters = SqlDataAccess.getResponses(advert.ID);
            return Json(sitters);
        }

        [HttpPost]
        public JsonResult GetDefaultLocation()
        {
            Parent parent = SqlDataAccess.getParentData(int.Parse(Session["parentID"].ToString()));
            return Json(parent);
        }

        [HttpPost]
        public int UpdateAdvert(string adv)
        {
            List<Advert> list = SqlDataAccess.getOpenAdverts(int.Parse(Session["parentID"].ToString()));
            Advert advert = list[int.Parse(Session["curAdvert"].ToString())];
            var js =  new JavaScriptSerializer();
            Advert newAdd = js.Deserialize<Advert>(adv);
            newAdd.ID = advert.ID;
            newAdd.DateCreated = advert.DateCreated;
            int valid = SqlDataAccess.updateAdvert(newAdd);
            if(valid == 1)
            {
                TempData["alertMessage"] = "Advert Succefully Updated";
                return 1;
            }else{
                TempData["errorMessage"] = "Error occured while creating Updating";
                return -1;
            }
        }

        [HttpPost]
        public int CloseAdvert()
        {
            if (Session["curAdvert"] != null)
            {
                List<Advert> list = SqlDataAccess.getOpenAdverts(int.Parse(Session["parentID"].ToString()));
                Advert advert = list[int.Parse(Session["curAdvert"].ToString())];
                SqlDataAccess.closeAdvert(advert);
                TempData["alertMessage"] = "Advert Succefully Closed Advert";
                return 1;
            }
            TempData["errorMessage"] = "Error occured while closing advert, try again...";
            return -1;
        }

        public ActionResult Logout()
        {
            Session.Clear();
            ViewData.Clear();
            TempData.Clear();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Settings()
        {
            if (Session["parentID"] == null)
            {
                return RedirectToAction("Parent_Login", "Home");
            }
            Parent parent = SqlDataAccess.getParentActualData(int.Parse(Session["parentID"].ToString()));
            parent.password = "";
            return View(parent);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Settings(Parent parent)
        {
            if (Session["parentID"] == null)
            {
                return RedirectToAction("Parent_Login", "Home");
            }
            int valid = SqlDataAccess.updateParentInfo(parent);
            if (valid == 1)
            {
                TempData["alertMessage"] = "Your information is Successfully Updated";
            }
            else
            {
                TempData["errorMessage"] = "There was an Error updating your infomation";
            }
            parent = SqlDataAccess.getParentActualData(int.Parse(Session["parentID"].ToString()));
            parent.password = "";
            return View(parent);
        }
   
        public int TestAjax(JsonResult id)
        {
            return int.Parse(id.ToString());
        }

    }
}

Best BabySitter/Controllers/SitterController.cs
using Best_BabySitter.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Best_BabySitter.Controllers
{
    public class SitterController : Controller
    {
        // GET: Sitter
        public ActionResult Index()
        {
            if (Session["SitterID"] == null)
            {
                return RedirectToAction("Sitter_Login", "Home");
            }
            TempData["OpenAdvert"] = SqlDataAccess.getOpenAdvertsForSitter(int.Parse(Session["SitterID"].ToString()));
            List<Appointment> appAd = SqlDataAccess.getAppointments(int.Parse(Session["SitterID"].ToString()), 2);
            List<Appointment> appSlot = SqlDataAccess.getSitterAppointmentSlots(int.Parse(Session["SitterID"].ToString()));
            TempData["createdSlots"] = SqlDataAccess.getSitterCreatedSlotCount(int.Parse(Session["SitterID"].ToString()));
            TempData["JobsDone"] = SqlDataAccess.getSitterJobDone(int.Parse(Session["SitterID"].ToString()));
            foreach (Appointment ap in appSlot)
            {
                appAd.Add(ap);
            }
            Sitter sitter = SqlDataAccess.getSitterActualData(Session["SitterID"].ToString());
            if (TempData["sitterCV"] != null)
            {
                string src = TempData["sitterCV"].ToString();
                // create the uploads folder if it doesn't exist
                Directory.CreateDirectory(Server.MapPath("~/Content/Sitters_Data/Sitter" + sitter.sitter_ID + "/"));
                string[] files = Directory.GetFiles("~/Content/Sitters_Data/temp/"+src);
                string path = "";
                foreach(string file in files)
                {
                    path = "~/Content/Sitters_Data/Sitter" + sitter.sitter_ID + "/" + Path.GetFileName(file);
                    Directory.Move(file,path);
                }
                sitter.cv_filePath = path;
                SqlDataAccess.updateSitterInfo(sitter);
            }
            Session["sitterCV"] = null;
            
            TempData["appointment"] = appAd;
            sitter.password = null;
            return View(sitter);
        }


        public ActionResult Advert(){
            if (Session["SitterID"] == null)
            {
                return RedirectToAction("Sitter_Login", "Home");
            }
            List<Advert> adverts = SqlDataAccess.getOpenAdvertsForSitter(int.Parse(Session["SitterID"].ToString()));
            return View(adverts);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Advert(Advert adver)
        {
            if (Session["curAdvert"] != null)
            {
                List<Advert> list = SqlDataAccess.getOpenAdvertsForSitter(int.Parse(Session["SitterID"].ToString()));
                if (list.Count > 0) {
                    Advert advert = list[int.Parse(Session["curAdvert"].ToString())];
                     int sitterID = int.Parse(Session["SitterID"].ToString());
                    if (Session["SitterID"] != null)
                    {
                        sitterID = int.Parse(Session["SitterID"].ToString());
                    }
                    bool validate = SqlDataAccess.applyForJob(sitterID, advert.ID);

                    if (validate)
                    {
                        TempData["alertMessage"] = "Succefully Applied For Job #AD0" + advert.ID;
                    }
                    else
                    {
                        TempData["errorMessage"] = "Error occured while applying for job,\n please try again\nor Contact Support Service";
                    } 
                }
                List<Advert> adverts = SqlDataAccess.getOpenAdvertsForSitter(int.Parse(Session["SitterID"].ToString()));
                Session["curAdvert"] = null;
                return View(adverts);
            }
            else
            {
                List<Advert> adverts = SqlDataAccess.getOpenAdvertsForSitter(int.Parse(Session["SitterID"].ToString()));
                return View(adverts);
            }
        }

        [HttpPost]
        public JsonResult AdvertDetail(string id)
        {
            int pos = int.Parse(id);
            Session["curAdvert"] = id;
            List<Advert> list = SqlDataAccess.getOpenAdvertsForSitter(int.Parse(Session["SitterID"].ToString()));
            Advert advert = list[int.Parse(Session["curAdvert"].ToString())];
            return Json(list[pos]);

        }


        public ActionResult Logout()
        {
            Session.Clear();
            TempData.Clear();
            ViewData.Clear();
            return RedirectToAction("Index", "Home");
        }

        public ActionResult Slots()
        {
            if (Session["SitterID"] == null)
            {
                return RedirectToAction("Sitter_Login", "Home");
            }
            List<Slot> slots = new List<Slot>();
            slots = SqlDataAccess.getSitterOpenSlots(int.Parse(Session["SitterID"].ToString()));
            return View(slots);
        }



        public ActionResult Settings()
        {
            if (Session["SitterID"] == null)
            {
                return RedirectToAction("Sitter_Login", "Home");
            }
            Sitter sitter = SqlDataAccess.getSitterData(Session["SitterID"].ToString());

            if (sitter != null)
            {
                sitter.password = "";
                return View(sitter);
            }
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Settings(Sitter sitter)
        {
            int valid = SqlDataAccess.updateSitterInfo(sitter);
            if(valid == 1)
            {
                TempData["alertMessage"] = "Your information is Successfully Updated";
            }
            else
            {
                TempData["errorMessage"] = "There was an Error updating your infomation";
            }
            sitter = SqlDataAccess.getSitterData(Session["SitterID"].ToString());

            if (sitter != null)
            {
                sitter.password = "";
                return View(sitter);
            }
            return View();
        }
    }
}

Best BabySitter/Views/Shared/_Admin.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Admin| @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="@Url.Content("~/Content/Images/logo.jpg")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="page">
        <header>
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Best BabySitter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Index", "Admin")</li>
                        <li>@Html.ActionLink("Verify Sitter", "Verify_Sitter", "Admin")</li>
                        <li>@Html.ActionLink("Suspend User", "Suspend_User", "Admin")</li>
                        <li>@Html.ActionLink("Settings", "Update_Info", "Admin")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Admin")</li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="parent-main-container">
            <section id="container">
                @RenderBody()
            </section>
        </div>
        <hr />
        <footer>
            <p></p>
        </footer>
    </div>
    <footer class="site-footer" style="position:relative">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h6>About</h6>
                    <p class="text-justify">BestBabySitter is a company that aims to provide services by creating a bridging between parents and people that are need of services such as taking care of children</p>
                </div>



                <div class="col-xs-6 col-md-3">
                    <h6>Quick Links</h6>
                    <ul class="footer-links">
                        <li><a href="/Admin/Index/">Dashboard</a></li>
                        <li><a href="/Admin/Verify_Sitter/">Advert</a></li>
                        <li><a href="/Admin/Suspend_User/">Slots</a></li>
                        <li><a href="/Admin/Update_Info/">Settings</a></li>
                        <li><a href="/Admin/Logout/">Logout</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy; @DateTime.Now.Year - Best-BabySitter All Rights Reserved by
                        <a href="#">Runtime Terror</a>.
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul class="social-icons">
                        <li><a class="facebook" href="#"><i class="fa fa-facebook-f"></i></a></li>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter-square"></i></a></li>
                        <li><a class="dribbble" href="#"><i class="fa fa-dribbble-square"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin-in"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Script")
    @RenderSection("scripts", required: false)
</body>
</html>

Best BabySitter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Best BabySitter|@ViewBag.Title</title>
    <link rel="icon" href="@Url.Content("~/Content/Images/logo.jpg")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            @Html.ActionLink("Best BabySitter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
        </div>
        <div class="navbar-collapse collapse ">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Home", "Index", "Home")</li>
                <li>@Html.ActionLink("Register as Parent", "Parent_Register", "Home")</li>
                <li>@Html.ActionLink("Login as Parent", "Parent_Login", "Home")</li>
                <li>@Html.ActionLink("Register as Sitter", "Sitter_Register", "Home")</li>
                <li>@Html.ActionLink("Login as Sitter", "Sitter_Login", "Home")</li>
                <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
            </ul>
        </div>
    </div>
    <div class="main-body-container">
        <div class="body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Best-BabySitter</p>
            </footer>
        </div>
    </div>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h6>About</h6>
                    <p class="text-justify">BestBabySitter is a company that aims to provide services by creating a bridging between parents and people that are need of services such as taking care of children</p>
                </div>

               

                <div class="col-xs-6 col-md-3">
                    <h6>Quick Links</h6>
                    <ul class="footer-links">
                        <li><a href="/Admin/Login/">Admin</a></li>
                        <li><a href="/Home/About/">About Us</a></li>
                        <li><a href="/Home/Contact/">Contact Us</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy; @DateTime.Now.Year - Best-BabySitter All Rights Reserved by
                        <a href="#">Runtime Terror</a>.
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul class="social-icons">
                        <li><a class="facebook" href="#"><i class="fa fa-facebook-f"></i></a></li>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter-square"></i></a></li>
                        <li><a class="dribbble" href="#"><i class="fa fa-dribbble-square"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin-in"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Script")

    @RenderSection("scripts", required: false)
</body>
</html>

Best BabySitter/Views/Shared/_ParentLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Parent| @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="@Url.Content("~/Content/Images/logo.jpg")">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="page">
        <header>
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Best BabySitter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Index", "Parent")</li>
                        <li>@Html.ActionLink("Sitters", "Sitters", "Parent")</li>
                        <li>@Html.ActionLink("Create Advert", "Create_Advert", "Parent")</li>
                        <li>@Html.ActionLink("Manage Advert", "Manage_Advert", "Parent")</li>
                        <li>@Html.ActionLink("Settings", "Settings", "Parent")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Parent")</li>
                    </ul>
                </div>
            </div>
        </header>
        <div class="parent-main-container">
            <section id="container">
                @RenderBody()
            </section>
        </div>
        <hr />
        <footer>
           
        </footer>
    </div>
    <footer class="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 col-md-6">
                    <h6>About</h6>
                    <p class="text-justify">BestBabySitter is a company that aims to provide services by creating a bridging between parents and people that are need of services such as taking care of children</p>
                </div>



                <div class="col-xs-6 col-md-3">
                    <h6>Quick Links</h6>
                    <ul class="footer-links">
                        <li><a href="/Parent/Index/">Dashboard</a></li>
                        <li><a href="/Parent/Sitters/">Find Sitters</a></li>
                        <li><a href="/Parent/Create_advert/">Create Advert</a></li>
                        <li><a href="/Parent/Manage_advert/">Manage Advert</a></li>
                        <li><a href="/Parent/Settings/">Settings</a></li>
                        <li><a href="/Parent/Logout/">Logout</a></li>
                    </ul>
                </div>
            </div>
            <hr>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-6 col-xs-12">
                    <p class="copyright-text">
                        Copyright &copy; @DateTime.Now.Year - Best-BabySitter All Rights Reserved by
                        <a href="#">Runtime Terror</a>.
                    </p>
                </div>

                <div class="col-md-4 col-sm-6 col-xs-12">
                    <ul class="social-icons">
                        <li><a class="facebook" href="#"><i class="fa fa-facebook-f"></i></a></li>
                        <li><a class="twitter" href="#"><i class="fa fa-twitter-square"></i></a></li>
                        <li><a class="dribbble" href="#"><i class="fa fa-dribbble-square"></i></a></li>
                        <li><a class="linkedin" href="#"><i class="fa fa-linkedin-in"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Script")
    @RenderSection("scripts", required: false)
</body>
</html>

Best BabySitter/Views/Shared/_SitterLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <title>Parent| @ViewBag.Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div id="page">
        <header>
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Best BabySitter", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Dashboard", "Index", "Sitter")</li>
                        <li>@Html.ActionLink("Profile", "Profile", "Sitter")</li>
                        <li>@Html.ActionLink("Adverts", "Adverts", "Sitter")</li>
                        <li>@Html.ActionLink("Slot", "Slots", "Sitter")</li>
                        <li>@Html.ActionLink("Settings", "Settings", "Sitter")</li>
                        <li>@Html.ActionLink("Logout", "Logout", "Sitter")</li>
                    </ul>
                </div>
            </div>
        </header>
        <section id="container">
            @RenderBody()
        </section>
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year </p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/Script")
    @RenderSection("scripts", required: false)
</body>
</html>